# Generated by Django 5.0 on 2026-02-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='headers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
